# Generated by Django 5.2.5 on 2025-08-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_models_viewlso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('trader_type', models.CharField(blank=True, choices=[('crypto', 'edrert'), ('dfsr', 'cypro')], max_length=34, null=True)),
                ('cypto_coins', models.CharField(blank=True, max_length=435, null=True)),
                ('forex_accouny_type', models.CharField(blank=True, max_length=54, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
